-- Lute and Lune mapping based on module output (Not fully tested)
--[[
File system
require("@lune/fs")
require("@lute/fs"
require("@lute/io") - C++?

-- Luau 
require("@lute/luau")
require("@lune/luau")

-- Networking
require("@lute/net")
require("@lune/net")

-- Process
require("@lute/process")
require("@lune/process") / require("@lute/system") extra details??

-- Task
require("@lute/task")
require("@lune/task")

-- Time
require("@lute/time")
require("@lune/datetime")

-- Json / whatever I forgor word
require("@lune/serde")

-- Roblox
require("@lune/roblox")

-- Uncategorized
require("@lune/stdio")
require("@lune/regex")
require("@lute/crypto")
require("@lute/debugger")
require("@lute/vm")
require("@lute/crypto")
require("@lute/crypto")
require("@lute/crypto")
]]
